### PR TITLE
fix(monitoring): restrict CNEC monitoring to preventive and last curative states (monitoring + result serialization) 

### LINKED ISSUE #1586: Inconsistent monitoring results
### Describe the current behavior

1. all curative states can be monitored
2. `RaoResultWithVoltageMonitoring::getCnecResult` only allow to retrieve results for curative states
3. same for AngleCNECs
4. Voltage and AngleCNECs results are serialized for any instant

### Describe the expected behavior

1. only curative states of the last curative instant should be monitored
2. `RaoResultWithVoltageMonitoring::getCnecResult` must allow to retrieve results for the preventive state or any curative state defined for the last curative state
3. same for AngleCNECs
4. Voltage and AngleCNECs results must be serialized only for final states (preventive and last curative)
5. remove call to safeGetValue

### Describe the steps

_No response_

### Environment

_No response_

### Relevant Log Output

_No response_

### Extra Information

_No response_

### PR DESCRIPTION
**Pull request by RoxaneChen02**
**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] A PR or issue has been opened in all impacted repositories (if any)

**Does this PR already have an issue describing the problem?**

Fixes #1586

- Monitor preventive cnec and last curative cnec only 

- Only TRY to serialize the voltage and angle cnec result if cnec's instant is preventive or last curative => if we expected a result but found NaN (means monitoring failed) => nothing is serialized 

- For RaoResultSerializer, serialize angle and voltage monitoring if in the execution details "went trough angle/voltage monitoring"

- For a given cnec defined at instant "Instant", you can only serialize/read cnec's result at this given instant "Instant" and only at this instant. 
-> getCnecResult(cnec, anotherInstant) => throw error

### CODE REVIEW

File: monitoring/src/main/java/com/powsybl/openrao/monitoring/results/RaoResultWithAngleMonitoring.java [hunk 1]
```diff
@@ -57,14 +62,18 @@ public SecurityStatus getSecurityStatus() {
         return angleMonitoringResult.getStatus();
     }
 
+    Optional<CnecResult> getCnecResult(Instant optimizationInstant, AngleCnec angleCnec) {
+        if (optimizationInstant == null || angleCnec.getState().getInstant() != optimizationInstant) {
+            throw new OpenRaoException("Unexpected optimization instant for angle monitoring result (only optimization instant equal to angle cnec' state's instant is accepted) : " + optimizationInstant);
```
Comment (bqth29) [inline monitoring/src/main/java/com/powsybl/openrao/monitoring/results/RaoResultWithAngleMonitoring.java]:
```suggestion
            throw new OpenRaoException("Unexpected optimization instant for angle monitoring result (only optimization instant equal to angle cnec's instant is accepted) : " + optimizationInstant);
```

File: monitoring/src/main/java/com/powsybl/openrao/monitoring/results/RaoResultWithVoltageMonitoring.java [hunk 2]
```diff
@@ -76,20 +81,16 @@ public double getMaxVoltage(Instant optimizationInstant, VoltageCnec voltageCnec
         }
     }
 
-    private Optional<CnecResult> getCnecResult(Instant optimizationInstant, VoltageCnec voltageCnec) {
-        if (optimizationInstant == null || !optimizationInstant.isCurative()) {
-            throw new OpenRaoException("Unexpected optimization instant for voltage monitoring result (only curative instant is supported currently) : " + optimizationInstant);
+    Optional<CnecResult> getCnecResult(Instant optimizationInstant, VoltageCnec voltageCnec) {
+        if (voltageCnec.getState().getInstant() != optimizationInstant) {
+            throw new OpenRaoException("Unexpected optimization instant for voltage monitoring result (only optimization instant equal to voltage cnec' state's instant is accepted) : " + optimizationInstant);
```
Comment (bqth29) [inline monitoring/src/main/java/com/powsybl/openrao/monitoring/results/RaoResultWithVoltageMonitoring.java]:
```suggestion
            throw new OpenRaoException("Unexpected optimization instant for voltage monitoring result (only optimization instant equal to voltage cnec's instant is accepted) : " + optimizationInstant);
```

File: monitoring/src/test/java/com/powsybl/openrao/monitoring/VoltageMonitoringTest.java [hunk 3]
```diff
@@ -612,4 +617,30 @@ void testWithComputationManager() throws IOException, InterruptedException {
         assertTrue(latch.await(5, TimeUnit.SECONDS));
         assertFalse(raoResultWithVoltageMonitoring.isSecure());
     }
+
+    @Test
+    void testVoltageMonitoringOfCnecsOnDifferentInstants() throws IOException {
```
Comment (bqth29) [inline monitoring/src/test/java/com/powsybl/openrao/monitoring/VoltageMonitoringTest.java]: can you just add a comment explaining why this test would not have passed before this PR please?

File: data/rao-result/rao-result-io/rao-result-json/src/main/java/com/powsybl/openrao/data/raoresult/io/json/serializers/RaoResultSerializer.java [hunk 4]
```diff
@@ -52,8 +52,12 @@ public void serialize(RaoResult raoResult, JsonGenerator jsonGenerator, Serializ
             CostResultMapSerializer.serialize(raoResult, crac, jsonGenerator);
             ComputationStatusMapSerializer.serialize(raoResult, crac, jsonGenerator);
             FlowCnecResultArraySerializer.serialize(raoResult, crac, flowUnits, jsonGenerator);
-            AngleCnecResultArraySerializer.serialize(raoResult, crac, jsonGenerator);
-            VoltageCnecResultArraySerializer.serialize(raoResult, crac, jsonGenerator);
+            if (raoResult.getExecutionDetails().contains("went through angle monitoring")) {
```
Comment (bqth29) [inline data/rao-result/rao-result-io/rao-result-json/src/main/java/com/powsybl/openrao/data/raoresult/io/json/serializers/RaoResultSerializer.java]: not a huge fan of checking that monitoring results exist this way, but I do not see any trivial solution
